### ISSUE TITLE
support for TS moduleResolution bundler, nodenext and node16

### ISSUE THREAD

**Issue by amalitsky** [descope/vue-sdk#20]
Hi folks and thanks for having this library in Vue! We at andromedasec are pleasantly surprised and very happy with it!

TS v5.0 [recently introduced](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler) a more DX-friendly and relevant module resolution strategies, such as `bundler`, `nodenext` & `node16` which we would like to use in our app.

For it to work all dependencies we use have to update as well, fortunately it is just `package.json` exports field update.

before:
```json
"types": "dist/index.d.ts",
"exports": {
  "require": "./dist/index.cjs",
  "import": "./dist/index.mjs"
},
``` 

after:
```json
"types": "dist/index.d.ts",
"exports": {
  "require": "./dist/index.cjs", // likely need to add types for CJS as well
  "import": {
    "default": "./dist/index.mjs",
    "types": "./dist/index.d.ts"
  }
}
``` 

Error I'm getting right now when using `moduleResolution: "bundler"` in my _tsconfig_:
```
error TS7016: Could not find a declaration file for module '@descope/vue-sdk'. '.../node_modules/@descope/vue-sdk/dist/index.mjs' implicitly has an 'any' type.
  There are types at .../node_modules/@descope/vue-sdk/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@descope/vue-sdk' library may need to update its package.json or typings.

2   import { useDescope } from '@descope/vue-sdk';
```

[Related discussion at TS repo](https://github.com/microsoft/TypeScript/issues/52363) with more context and recommended solution.

Does this look interesting or important enough to add to the backlog?

Thank you
Alex

**Comment by asafshen** [comment]
Hey Alex, Thanks for the detailed information 

yes, this is absolutely possible, let me check that and I will update here on this issue soon   

(FYI I think that other Descope JS sdks such as react-sdk already supports this in its [package.json](https://github.com/descope/react-sdk/blob/main/package.json#L17)

**Comment by asafshen** [comment]
@amalitsky thanks for the feedback! 

the fix will be avaialble in the next release 

in the meantime, you can use the latest `next` tag (`@descope/vue-sdk@0.0.0-next-2dc1dceb-20230827`)

if there is any further query or issue, please let me know!

**Comment by amalitsky** [comment]
Thanks for the fast turn-around, we will wait for the next release 🎉
